language: generic
sudo: required
dist: trusty

services:
- docker

install:
- git reset --hard

script:
- export KUBEVIRT_UPDATE_CACHE_FROM="${TRAVIS_BRANCH}"
- export KUBEVIRT_CACHE_FROM="${TRAVIS_BRANCH}"
- if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then make pull-cache; fi # only use the cache in PRs, rebuild otherwise
- make generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make generate`. Please run it and commit the changes"; git status --porcelain; false; fi
- if diff <(git grep -c '') <(git grep -cI '') | egrep -v -e 'docs/.*\.png|swagger-ui' -e 'vendor/*' -e 'assets/*'
  | grep '^<'; then echo "Binary files are present in git repostory."; false; fi
- make build
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make`. Please run it and commit the changes"; git status --porcelain; false; fi
- if [[ $TRAVIS_REPO_SLUG == "kubevirt/kubevirt" ]]; then make goveralls; else make bazel-tests; fi
- make apidocs
- make client-python
- make manifests DOCKER_PREFIX="docker.io/kubevirt" DOCKER_TAG=$TRAVIS_TAG # skip getting old CSVs here (no QUAY_REPOSITORY), verification might fail because of stricter rules over time; falls back to latest if not on a tag
- make olm-verify

deploy:
- provider: script
  script: make bazel-build-images
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: make push-cache
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $TRAVIS_BRANCH != revert-*
